dist: trusty
sudo: required
language:
    - cpp
compiler:
    - gcc
      #- clang
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
              #- llvm-toolchain-precise-3.6
        packages:
            - gcc-6
            - g++-6
            - cmake
            - clang-3.6
        script:
            Link gcc-6 and g++-6 to their standard commands
            - ln -s /usr/bin/gcc-6 /usr/local/bin/gcc
            - ln -s /usr/bin/g++-6 /usr/local/bin/g++
            # Export CC and CXX to tell cmake which compiler to use
            - export CC=/usr/bin/gcc-6
            - export CXX=/usr/bin/g++-6
            # Check versions of gcc, g++ and cmake
            - gcc -v && g++ -v && cmake --version
            # Run your build commands next

before_script:
    - cd ./qwer_main
    - mkdir bin
    - cd bin
    - cmake ..
    - make

script: ctest -V
